name: lunarreg
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - alsa-lib
  - aom
  - brotli
  - brotli-bin
  - bzip2
  - c-ares
  - ca-certificates
  - cairo
  - certifi
  - cycler
  - dbus
  - expat
  - ffmpeg
  - fontconfig
  - fonttools
  - freeglut
  - freetype
  - gettext
  - glib
  - glib-tools
  - gmp
  - gnutls
  - graphite2
  - gst-plugins-base
  - gstreamer
  - harfbuzz
  - hdf5
  - icu
  - jasper
  - jbig
  - jpeg
  - kiwisolver
  - krb5
  - lame
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libclang
  - libcurl
  - libdeflate
  - libdrm
  - libedit
  - libev
  - libevent
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libiconv
  - liblapack
  - liblapacke
  - libllvm11
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopencv
  - libopus
  - libpciaccess
  - libpng
  - libpq
  - libprotobuf
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libva
  - libvorbis
  - libvpx
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libzlib
  - lz4-c
  - matplotlib
  - matplotlib-base
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - nettle
  - nspr
  - nss
  - numpy
  - olefile
  - opencv
  - openh264
  - openjpeg
  - openssl
  - packaging
  - pcre
  - pillow
  - pip
  - pixman
  - pthread-stubs
  - py-opencv
  - pyparsing
  - pyqt
  - pyqt-impl
  - pyqt5-sip
  - pyqtchart
  - pyqtwebengine
  - python
  - python-dateutil
  - python_abi
  - qt
  - readline
  - setuptools
  - six
  - sqlite
  - svt-av1
  - tk
  - tornado
  - tzdata
  - x264
  - x265
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xz
  - zlib
  - zstd
  - pip:
    - build
    - pep517
    - tomli
    - wheel
